version: '3'

services:
  db:
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
